### ISSUE TITLE
rubocop doesn't add changes to commit

### ISSUE THREAD

**Issue by alexanderkraemer** [runtastic/rubocop_runner#1]
On commit, rubocop starts to scan modified files.
If rubocop doesn't find any needed modifications, your changes will be commited.
If rubocop does find unclean code passages, he changes them, and then commits, without adding the modified changes to the commit.

**Comment by nilsding** [comment]
To make it more clear, here is how to reproduce this behaviour:

``` sh
[nilsding:~/tmp/rubocop_runner]$ ruby -rrubocop_runner -e "RubocopRunner.install"
[nilsding:~/tmp/rubocop_runner]$ echo 'hash={a: 2}\n puts hash.inspect' > code.rb
[nilsding:~/tmp/rubocop_runner]$ git add code.rb
[nilsding:~/tmp/rubocop_runner]$ git commit -vm 'commit message'
code.rb:1:5: C: [Corrected] Surrounding space missing for operator =.
hash={a: 2}
    ^
code.rb:1:6: C: [Corrected] Space inside { missing.
hash={a: 2}
     ^
code.rb:1:11: C: [Corrected] Space inside } missing.
hash={a: 2}
          ^
code.rb:2:2: C: [Corrected] Inconsistent indentation detected.
 puts hash.inspect
 ^^^^^^^^^^^^^^^^^
 1/1 file |==================== 100 ======================>| Time: 00:00:00

1 file inspected, 4 offenses detected, 4 offenses corrected
[nilsding:~/tmp/rubocop_runner]$ git status
On branch master

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

	new file:   code.rb

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   code.rb
```

What should happen in the case Rubocop automatically fixes something is that all modified files which have been already added before should be added again.

**Comment by andreaseger** [comment]
actually this is expected behavior. If everything is fine the pre-commit hook exits successfully and the commit goes on like normal.
If rubocop auto-corrects things the pre-commit hook exits with a failing status codes which aborts commit without staging the auto-corrected changes.

This can't reliably be automated because rubocop or this gem act on files while git acts on patches. So while rubocop/this gem looks at the whole file not necessarily the whole file was part of the commit. For example if you only stage parts of a file using `git add -p` rubocop will still check and auto-correct the whole file. Adding the relevant changes back to the commit has to be left up to the user/developer.
